name: Build & Package Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Package extension
        shell: pwsh
        run: |
          ./pack.ps1 -OutFile affiliate-rewards-extension.zip
          Get-ChildItem -Path affiliate-rewards-extension.zip | Format-List

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: affiliate-rewards-extension.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
